### ISSUE TITLE
Feedback video shows out of the cell on "View all submissions" page

### ISSUE THREAD

**Issue by izendegi** [justinhunt/moodle-assignfeedback_poodll#4]
Hi,

We've detected that with the 3.1.027(Build 2021052000) version of this plugin the video, when viewing the "View all submissions" page of an assignment the video on the Feedback Poodll column shows outside its cell (on top of the table) and makes the table unclickable unless you hide that column. We've tested it on Moodle 3.9 and 3.10 with several themes (both core and plugins).

This doesn't happen with the previous 3.1.025(Build 2020112000) version.

**Comment by KepaUrzelai** [comment]
Hello @izendegi,

I've seen that the problem comes from the next css property in the style.css file:
`.assignfeedback_poodll_video {
 position: absolute;
 top: 0;
 left: 0;
 width: 100%;
 height: 100%;
}`

Setting the `position` to `static` does the work and fixes your issue.

**Comment by izendegi** [comment]
Hi,

Thanks @KepaUrzelai !

After looking into the commit history of that file and what @KepaUrzelai has proposed, I've been playing around with it and I think that this one would show up better:

> .assignfeedback_poodll_video {
>    position: static;
>    max-width: 480px;
>    min-width: 220px;
>    width: 100%;
> }

BTW, the padding-bottom feature added recently to that file seems thought to be applied to small screens for responsiveness but it's currently added also on big screens and it displays an extra empty space that feels like it shouldn't be there.

**Comment by justinhunt** [comment]
Thanks for this. I will test the code tomorrow and report back. yes we worked on the responsive features in the last release. So its related to that.

**Comment by justinhunt** [comment]
Sorry for the delay in testing. I am not able to reproduce the issue @izendegi posted. 
The padding-bottom was pretty fiddly to get right though. 
I wonder what Theme/Moodle-version you are using?
And can you post a screenshot?

**Comment by KepaUrzelai** [comment]
Hello @justinhunt,

Thank you for your reply. 
As @izendegi pointed in the issue opening message, we were able to reproduce the issue in Moodle version 3.10 and 3.9, with Boost, Fordson and Moove themes, among others.

Here is the screenshot, where you can see how the Feedback Poodll video is shown out of its cell:
![imagen](https://user-images.githubusercontent.com/43538080/120983149-b6fdf900-c779-11eb-8e7a-29919e97c9a0.png)

**Comment by justinhunt** [comment]
OK the latest commit should have fixed this. Thanks for the heads up.  There were a few styles that I left out, so the padding and full size issues should both be resolved.

**Comment by KepaUrzelai** [comment]
Hi @justinhunt,

We've tested your patch and the issue has been resolved :) 
Thanks a lot for your work!
